<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class WooCompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'MadeByDenis\\WooSoloApi\\Database\\SoloOrdersTable' => 'get1',
  'MadeByDenis\\WooSoloApi\\ECommerce\\WooCommerce\\WooPaymentGateways' => 'get2',
  'MadeByDenis\\WooSoloApi\\Request\\SoloApiRequest' => 'get3',
  'MadeByDenis\\WooSoloApi\\BackgroundJobs\\SendCustomerEmail' => 'get4',
  'MadeByDenis\\WooSoloApi\\BackgroundJobs\\MakeSoloApiCall' => 'get5',
  'subEntry1' => 'get6',
  'MadeByDenis\\WooSoloApi\\Rest\\ModifySettingsRoute' => 'get7',
  'MadeByDenis\\WooSoloApi\\Rest\\Endpoints\\ClearExchangeTransient' => 'get8',
  'MadeByDenis\\WooSoloApi\\Rest\\Endpoints\\GetSettings' => 'get9',
  'subEntry2' => 'get10',
  'MadeByDenis\\WooSoloApi\\Rest\\Endpoints\\OrderDetails' => 'get11',
  'subEntry3' => 'get12',
  'MadeByDenis\\WooSoloApi\\Rest\\Endpoints\\AccountDetails' => 'get13',
  'MadeByDenis\\WooSoloApi\\Rest\\Endpoints\\OrderDetailsCollection' => 'get14',
  'subEntry4' => 'get15',
  'MadeByDenis\\WooSoloApi\\Rest\\Endpoints\\ResendApiOrder' => 'get16',
  'subEntry5' => 'get17',
  'MadeByDenis\\WooSoloApi\\Email\\EmailFunctionality' => 'get18',
  'MadeByDenis\\WooSoloApi\\Assets\\EnqueueResources' => 'get19',
  'MadeByDenis\\WooSoloApi\\i18n\\Internationalization' => 'get20',
  'MadeByDenis\\WooSoloApi\\Utils\\FetchExchangeRate' => 'get21',
  'MadeByDenis\\WooSoloApi\\Admin\\AdminMenus\\OptionsSubmenu' => 'get22',
  'MadeByDenis\\WooSoloApi\\Admin\\AdminNotices\\DatabaseTableMissingNotice' => 'get23',
  'subEntry6' => 'get24',
  'MadeByDenis\\WooSoloApi\\Admin\\PluginsPage' => 'get25',
  'MadeByDenis\\WooSoloApi\\Privacy\\DataHandling' => 'get26',
  'subEntry7' => 'get27',
  'MadeByDenis\\WooSoloApi\\ECommerce\\WooCommerce\\MakeApiRequest' => 'get28',
  'subEntry8' => 'get29',
  'subEntry9' => 'get30',
  'MadeByDenis\\WooSoloApi\\ECommerce\\WooCommerce\\AdminOrder' => 'get31',
  'MadeByDenis\\WooSoloApi\\ECommerce\\WooCommerce\\CheckoutFields' => 'get32',
  'MadeByDenis\\WooSoloApi\\Settings\\PluginSettings' => 'get33',
  'subEntry10' => 'get34',
);

    protected function get1()
    {
        $object = new MadeByDenis\WooSoloApi\Database\SoloOrdersTable();
        return $object;
    }

    protected function get2()
    {
        $object = new MadeByDenis\WooSoloApi\ECommerce\WooCommerce\WooPaymentGateways();
        return $object;
    }

    protected function get3()
    {
        $object = new MadeByDenis\WooSoloApi\Request\SoloApiRequest();
        return $object;
    }

    protected function get4()
    {
        $object = new MadeByDenis\WooSoloApi\BackgroundJobs\SendCustomerEmail();
        return $object;
    }

    protected function get6()
    {
        return $this->delegateContainer->get('MadeByDenis\\WooSoloApi\\Request\\SoloApiRequest');
    }

    protected function get5()
    {
        $object = new MadeByDenis\WooSoloApi\BackgroundJobs\MakeSoloApiCall($this->get6());
        return $object;
    }

    protected function get7()
    {
        $object = new MadeByDenis\WooSoloApi\Rest\ModifySettingsRoute();
        return $object;
    }

    protected function get8()
    {
        $object = new MadeByDenis\WooSoloApi\Rest\Endpoints\ClearExchangeTransient();
        return $object;
    }

    protected function get10()
    {
        return $this->delegateContainer->get('MadeByDenis\\WooSoloApi\\ECommerce\\WooCommerce\\WooPaymentGateways');
    }

    protected function get9()
    {
        $object = new MadeByDenis\WooSoloApi\Rest\Endpoints\GetSettings($this->get10());
        return $object;
    }

    protected function get12()
    {
        return $this->delegateContainer->get('MadeByDenis\\WooSoloApi\\Database\\SoloOrdersTable');
    }

    protected function get11()
    {
        $object = new MadeByDenis\WooSoloApi\Rest\Endpoints\OrderDetails($this->get12());
        return $object;
    }

    protected function get13()
    {
        $object = new MadeByDenis\WooSoloApi\Rest\Endpoints\AccountDetails();
        return $object;
    }

    protected function get15()
    {
        return $this->delegateContainer->get('MadeByDenis\\WooSoloApi\\Database\\SoloOrdersTable');
    }

    protected function get14()
    {
        $object = new MadeByDenis\WooSoloApi\Rest\Endpoints\OrderDetailsCollection($this->get15());
        return $object;
    }

    protected function get17()
    {
        return $this->delegateContainer->get('MadeByDenis\\WooSoloApi\\Request\\SoloApiRequest');
    }

    protected function get16()
    {
        $object = new MadeByDenis\WooSoloApi\Rest\Endpoints\ResendApiOrder($this->get17());
        return $object;
    }

    protected function get18()
    {
        $object = new MadeByDenis\WooSoloApi\Email\EmailFunctionality();
        return $object;
    }

    protected function get19()
    {
        $object = new MadeByDenis\WooSoloApi\Assets\EnqueueResources();
        return $object;
    }

    protected function get20()
    {
        $object = new MadeByDenis\WooSoloApi\i18n\Internationalization();
        return $object;
    }

    protected function get21()
    {
        $object = new MadeByDenis\WooSoloApi\Utils\FetchExchangeRate();
        return $object;
    }

    protected function get22()
    {
        $object = new MadeByDenis\WooSoloApi\Admin\AdminMenus\OptionsSubmenu();
        return $object;
    }

    protected function get24()
    {
        return $this->delegateContainer->get('MadeByDenis\\WooSoloApi\\Database\\SoloOrdersTable');
    }

    protected function get23()
    {
        $object = new MadeByDenis\WooSoloApi\Admin\AdminNotices\DatabaseTableMissingNotice($this->get24());
        return $object;
    }

    protected function get25()
    {
        $object = new MadeByDenis\WooSoloApi\Admin\PluginsPage();
        return $object;
    }

    protected function get27()
    {
        return $this->delegateContainer->get('MadeByDenis\\WooSoloApi\\Database\\SoloOrdersTable');
    }

    protected function get26()
    {
        $object = new MadeByDenis\WooSoloApi\Privacy\DataHandling($this->get27());
        return $object;
    }

    protected function get29()
    {
        return $this->delegateContainer->get('MadeByDenis\\WooSoloApi\\Database\\SoloOrdersTable');
    }

    protected function get30()
    {
        return $this->delegateContainer->get('MadeByDenis\\WooSoloApi\\Request\\SoloApiRequest');
    }

    protected function get28()
    {
        $object = new MadeByDenis\WooSoloApi\ECommerce\WooCommerce\MakeApiRequest($this->get29(), $this->get30());
        return $object;
    }

    protected function get31()
    {
        $object = new MadeByDenis\WooSoloApi\ECommerce\WooCommerce\AdminOrder();
        return $object;
    }

    protected function get32()
    {
        $object = new MadeByDenis\WooSoloApi\ECommerce\WooCommerce\CheckoutFields();
        return $object;
    }

    protected function get34()
    {
        return $this->delegateContainer->get('MadeByDenis\\WooSoloApi\\ECommerce\\WooCommerce\\WooPaymentGateways');
    }

    protected function get33()
    {
        $object = new MadeByDenis\WooSoloApi\Settings\PluginSettings($this->get34());
        return $object;
    }

}
